# Generated by Django 4.2.13 on 2024-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutionApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_description',
            field=models.TextField(default=''),
        ),
    ]
