# Generated by Django 4.2.13 on 2024-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutionApp', '0003_comment_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_description',
            field=models.TextField(),
        ),
    ]
